#!/usr/bin/env bash
# .devcontainer/scripts/post-create.sh
#
# Runs once after the devcontainer is created (postCreateCommand).
# Every step is idempotent — safe to re-run manually at any time.
#
# Steps
#   1. Register QEMU binfmt handlers (arm, aarch64)
#   2. Create Docker buildx instance   (rpi-builder)
#   3. Pull ARM base image             (debian:bookworm-slim for arm/v7)
#   4. Install Python packages         (gpiozero, RPi.GPIO-stubs, picamera2-stubs)
#   5. Write ~/.zsh_aliases
#   6. Source aliases from ~/.zshrc
#   7. Mark this script executable
#   8. Print quick-reference summary

set -euo pipefail

# ── Colour helpers ─────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

step() { echo -e "\n${BOLD}${CYAN}>>>${RESET} ${BOLD}$*${RESET}"; }
ok()   { echo -e "    ${GREEN}ok${RESET}   $*"; }
warn() { echo -e "    ${YELLOW}warn${RESET} $*"; }

echo -e "\n${BOLD}======================================================${RESET}"
echo -e "${BOLD}   Raspberry Pi Devcontainer — post-create setup${RESET}"
echo -e "${BOLD}======================================================${RESET}"

# ── 0. Wait for Docker daemon to be ready ─────────────────────────────────────
step "Waiting for Docker daemon..."

# Work around Docker client/server API version mismatch in Codespaces
export DOCKER_API_VERSION=1.43

# Fix socket permissions if needed (Docker-in-Docker may create with wrong gid)
if [ -S /var/run/docker.sock ]; then
    sudo chown root:docker /var/run/docker.sock 2>/dev/null || true
fi

DOCKER_TIMEOUT=30
for i in $(seq 1 $DOCKER_TIMEOUT); do
    if docker info &>/dev/null; then
        ok "Docker daemon is ready (took ${i}s)."
        break
    fi
    if [ "$i" -eq "$DOCKER_TIMEOUT" ]; then
        warn "Docker daemon not ready after ${DOCKER_TIMEOUT}s — skipping Docker-dependent steps."
        DOCKER_READY=false
    fi
    sleep 1
done
DOCKER_READY=${DOCKER_READY:-true}

# ── 1. Register QEMU binfmt handlers ──────────────────────────────────────────
step "Registering QEMU binfmt handlers (arm, aarch64)..."
if [ "$DOCKER_READY" = "true" ] && docker run --privileged --rm tonistiigi/binfmt --install arm,aarch64 2>/dev/null; then
    ok "binfmt handlers registered via tonistiigi/binfmt."
else
    warn "tonistiigi/binfmt failed or Docker not ready."
    warn "Falling back to update-binfmts (may be a no-op inside the container)."
    update-binfmts --enable qemu-arm     2>/dev/null || true
    update-binfmts --enable qemu-aarch64 2>/dev/null || true
    ok "Fallback complete. QEMU binfmt will be re-registered on next privileged run."
fi

# ── 2. Create Docker buildx instance ──────────────────────────────────────────
step "Configuring Docker buildx instance 'rpi-builder'..."
if [ "$DOCKER_READY" != "true" ]; then
    warn "Docker not ready — skipping buildx configuration."
elif docker buildx inspect rpi-builder &>/dev/null; then
    ok "rpi-builder already exists — skipping creation."
else
    docker buildx create \
        --name rpi-builder \
        --driver docker-container \
        --platform linux/arm/v7,linux/arm64,linux/amd64 \
        --use
    docker buildx inspect --bootstrap rpi-builder
    ok "rpi-builder created and bootstrapped."
fi
# Ensure rpi-builder is the active builder for the current session.
[ "$DOCKER_READY" = "true" ] && docker buildx use rpi-builder 2>/dev/null || true

# ── 3. Pull ARM base image ─────────────────────────────────────────────────────
step "Pulling ARM base image (debian:bookworm-slim, linux/arm/v7)..."
if [ "$DOCKER_READY" != "true" ]; then
    warn "Docker not ready — skipping image pull."
elif docker pull --platform linux/arm/v7 debian:bookworm-slim; then
    ok "debian:bookworm-slim (arm/v7) cached."
else
    warn "Pull failed — image will be fetched on first use."
fi

# ── 4. Install Python packages ─────────────────────────────────────────────────
step "Installing Python packages..."

pip install --quiet --upgrade pip setuptools wheel \
    && ok "pip / setuptools / wheel up to date."

# Core packages — failures are surfaced as warnings, not errors.
for pkg in gpiozero picamera2; do
    if pip install --quiet "$pkg" 2>/dev/null; then
        ok "Installed $pkg"
    else
        warn "Could not install $pkg — skipping (non-fatal)."
    fi
done

# Type-stub packages — pure development-time helpers; always non-fatal.
for stub in "RPi.GPIO-stubs" "picamera2-stubs"; do
    if pip install --quiet "$stub" 2>/dev/null; then
        ok "Installed stub: $stub"
    else
        warn "Stub not available: $stub — skipping (non-fatal)."
    fi
done

# ── 5. Write ~/.zsh_aliases ────────────────────────────────────────────────────
step "Writing ~/.zsh_aliases..."
ALIAS_FILE="$HOME/.zsh_aliases"

cat > "$ALIAS_FILE" << 'ALIASES'
# =============================================================================
# Raspberry Pi Devcontainer — shell aliases
# Auto-generated by .devcontainer/scripts/post-create.sh
# =============================================================================

# ── Interactive ARM shells (Docker + QEMU transparent emulation) ──────────────

# Drop into a Debian bookworm shell running under ARMv7 (Pi 2/3/4 32-bit OS)
alias rpi-shell='docker run --rm -it --platform linux/arm/v7 \
    -v "$PWD:/workspace" -w /workspace debian:bookworm-slim /bin/bash'

# Drop into a Debian bookworm shell running under AArch64 (Pi 3/4/5 64-bit OS)
alias rpi-shell64='docker run --rm -it --platform linux/arm64 \
    -v "$PWD:/workspace" -w /workspace debian:bookworm-slim /bin/bash'

# ── Cross-compilers ────────────────────────────────────────────────────────────

# 32-bit ARMv7 hard-float (Raspberry Pi OS 32-bit)
alias rpi-gcc='arm-linux-gnueabihf-gcc'
alias rpi-g++='arm-linux-gnueabihf-g++'

# 64-bit AArch64 (Raspberry Pi OS 64-bit)
alias rpi-gcc64='aarch64-linux-gnu-gcc'
alias rpi-g++64='aarch64-linux-gnu-g++'

# ── QEMU user-mode binary runners ─────────────────────────────────────────────

# Run an ARMv7 binary on the host via QEMU user-mode emulation.
# The -L flag points to the dynamic linker / shared-lib prefix.
alias rpi-run='qemu-arm -L /usr/arm-linux-gnueabihf'

# Run an AArch64 binary on the host via QEMU user-mode emulation.
alias rpi-run64='qemu-aarch64 -L /usr/aarch64-linux-gnu'

# ── CMake cross-compilation wrappers ──────────────────────────────────────────

# Configure a CMake project targeting ARMv7.
# Example: rpi-cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
alias rpi-cmake='cmake -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/rpi-armv7.cmake'

# Configure a CMake project targeting AArch64.
# Example: rpi-cmake64 -DCMAKE_BUILD_TYPE=Release -S . -B build
alias rpi-cmake64='cmake -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/rpi-aarch64.cmake'

# ── Docker buildx shortcuts ────────────────────────────────────────────────────

# Build a container image targeting linux/arm/v7 with the rpi-builder instance.
# Example: rpi-docker-build -t myimage:latest --push .
alias rpi-docker-build='docker buildx build --builder rpi-builder --platform linux/arm/v7'

# Build a container image targeting linux/arm64.
alias rpi-docker-build64='docker buildx build --builder rpi-builder --platform linux/arm64'

# ── Deploy to Raspberry Pi via rsync ──────────────────────────────────────────
#
# Usage: rpi-deploy [local-src] [remote-dest]
#   local-src   defaults to the current directory (.)
#   remote-dest defaults to /home/pi/app
#
# Requires RPI_HOST to be set before calling, e.g.:
#   export RPI_HOST=pi@192.168.1.100
#
rpi-deploy() {
    local host="${RPI_HOST:?RPI_HOST is not set. Export it first, e.g.: export RPI_HOST=pi@192.168.1.100}"
    local src="${1:-.}"
    local dest="${2:-/home/pi/app}"

    echo "Deploying '$src'  ->  $host:$dest"
    rsync -avz --progress \
        --exclude '.git/' \
        --exclude 'build/' \
        --exclude 'build_*/' \
        --exclude 'node_modules/' \
        --exclude '__pycache__/' \
        --exclude '*.pyc' \
        --exclude '.DS_Store' \
        "$src" "$host:$dest"
}

# ── Docker Compose network helpers ────────────────────────────────────────────
# These aliases assume a docker-compose.yml lives under network/ in the repo.

# Start all services in detached mode, rebuilding any changed images.
alias rpi-net-up='docker compose -f network/docker-compose.yml up --build -d'

# Stop all services and remove named volumes.
alias rpi-net-down='docker compose -f network/docker-compose.yml down -v'

# Stream logs from all running services.
alias rpi-net-logs='docker compose -f network/docker-compose.yml logs -f'

# Show the running status of all services.
alias rpi-net-ps='docker compose -f network/docker-compose.yml ps'
ALIASES

ok "~/.zsh_aliases written."

# ── 6. Source aliases from ~/.zshrc ───────────────────────────────────────────
step "Ensuring ~/.zsh_aliases is sourced from ~/.zshrc..."
ZSHRC="$HOME/.zshrc"
SOURCE_LINE='[[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases'

if grep -qF 'zsh_aliases' "$ZSHRC" 2>/dev/null; then
    ok "~/.zshrc already sources ~/.zsh_aliases — no change needed."
else
    {
        printf '\n# Raspberry Pi devcontainer aliases\n'
        printf '%s\n' "$SOURCE_LINE"
    } >> "$ZSHRC"
    ok "Source line added to ~/.zshrc."
fi

# ── 7. Ensure this script is executable ───────────────────────────────────────
SCRIPT_PATH="$(realpath "$0" 2>/dev/null || echo ".devcontainer/scripts/post-create.sh")"
chmod +x "$SCRIPT_PATH" 2>/dev/null || true

# ── 8. Quick-reference summary ────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}======================================================"
echo -e "  Raspberry Pi Devcontainer — Ready!"
echo -e "======================================================${RESET}"
echo ""
echo -e "${BOLD}Cross-compilers${RESET}"
echo "  rpi-gcc  / rpi-g++          Compile for ARMv7 32-bit (Pi 2/3/4)"
echo "  rpi-gcc64 / rpi-g++64       Compile for AArch64 64-bit (Pi 3/4/5)"
echo ""
echo -e "${BOLD}Run ARM binaries locally (QEMU)${RESET}"
echo "  rpi-run <binary>            Execute ARMv7 binary via qemu-arm"
echo "  rpi-run64 <binary>          Execute AArch64 binary via qemu-aarch64"
echo ""
echo -e "${BOLD}CMake cross-compilation${RESET}"
echo "  rpi-cmake [args]            Configure project with ARMv7 toolchain"
echo "  rpi-cmake64 [args]          Configure project with AArch64 toolchain"
echo ""
echo -e "${BOLD}Interactive ARM shells${RESET}"
echo "  rpi-shell                   Debian bookworm shell (linux/arm/v7)"
echo "  rpi-shell64                 Debian bookworm shell (linux/arm64)"
echo ""
echo -e "${BOLD}Docker buildx${RESET}"
echo "  rpi-docker-build [args]     Build image for linux/arm/v7"
echo "  rpi-docker-build64 [args]   Build image for linux/arm64"
echo ""
echo -e "${BOLD}Deploy to Pi${RESET}"
echo "  export RPI_HOST=pi@<ip>     Set target Raspberry Pi host"
echo "  rpi-deploy [src] [dest]     Rsync to Pi (default: . -> /home/pi/app)"
echo ""
echo -e "${BOLD}Network (docker compose)${RESET}"
echo "  rpi-net-up                  Start multi-node network (rebuild images)"
echo "  rpi-net-down                Stop network and remove volumes"
echo "  rpi-net-logs                Stream service logs"
echo "  rpi-net-ps                  Show service status"
echo ""
echo -e "Aliases are available in every new ${BOLD}zsh${RESET} session."
echo -e "To use them right now:  ${BOLD}source ~/.zsh_aliases${RESET}"
echo ""
